version: 2.1
orbs:
  tfenv: sogaoh/orb-tfenv@0.0.1

jobs:
  build:
    docker:
    - image: amazonlinux:2
    parameters:
      terraform_version:
        description: version of terraform
        type: string
        default: 1.0.5
    steps:
    - run:
       name: Install Tools (PreRequirements for orb-tfenv)
       command: |
         yum install -y git unzip
    - tfenv/install
    - run:
        name: Install terraform & Show Version
        command: |
          VERSION="<< parameters.terraform_version >>"
          tfenv install ${VERSION} 
          tfenv use ${VERSION}
          terraform --version

workflows:
  main:
    jobs:
    - build